---
- name: Update existing packages
  apt:
    name: "*"
    state: latest

- name: Install containerd and utils
  apt:
    pkg:
      - apt-transport-https 
      - ca-certificates
      - containerd
      - curl

- name: Add Kubernetes signing key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    state: present

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: deb https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /
    state: present
    filename: kubernetes.list

- name: Install Kubernetes tools
  apt:
    update-cache: yes
    state: present
    pkg:
      - kubeadm={{ kubernetes_version }}
      - kubectl={{ kubernetes_version }}
      - kubelet={{ kubernetes_version }}
