---
  - hosts: all
    become: true
    roles:
      - role: ../../roles/kubernetes/common
        become: yes
      - role: ../../roles/kubernetes/node
        become: yes

    handlers:
      - name: Check container runtime status
        service: name=containerd state=started